### ISSUE TITLE
Labels 

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#1]
The label of the displayed entities should be computed via a labeller (an object getting a string and
returning a string). A dummy labeller is identity. Defining other labellers is outside the scope of the
project.
Any entity with a label should offer a way to get that label from that entity

**Comment by akevalion** [comment]
Update from pdf from Nicolas

Labels: I did not check how they are computed, but this should be configurable by the user
(us): "The label of the displayed entities should be computed via a labeller (an object getting
a string and returning a string)."

**Comment by akevalion** [comment]
Currently, we have an object called HLabeler

**Comment by NicolasAnquetil** [comment]
This issue can be closed
