### ISSUE TITLE
Container Expansion. 

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#11]
Containers can be expanded on demand, through contextual menus and / or mouse clicks or via
an API call. Expanded means that instead of seeing a container we will the container and the
element it contains

**Comment by akevalion** [comment]
an HNode responds to `collapse` or `expand` methods, this methods change the visibility of the node and notifies a change to the visualization.

The visualization also puts a contextual menu to collapse or expand the node

![image](https://user-images.githubusercontent.com/10532890/123290075-f8fb9e80-d4de-11eb-9242-a6b20af12e9a.png)

**Comment by akevalion** [comment]
update of this behavior

![image](https://user-images.githubusercontent.com/10532890/125814753-0adbb8bc-91ee-47aa-a584-1a21d4274b32.png)

**Comment by bergel** [comment]
Fixed
