### ISSUE TITLE
Visibility of relations. 

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#12]
The visibility of the various relations should be able parametrised: We may not want to see the
relationship between other containers and the elements of an expanded containers.
From a particular element, elements in relations may be visible through a menu and edges will be
added accordingly, through a specified declaration.
This feature should be available

- through an individual action on each entity (show/hide incoming/outgoing relations menu)
- through an API (show/hide incoming/outgoing relations of a given entity.

**Comment by bergel** [comment]
This issue can be closed. Right click on an edge does the job...
