### ISSUE TITLE
Drill Down. 

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#13]
The visualisation should support drill down on a container.
It means that the existing visible elements and their position should be pushed on a stack and that
the container elements should be displayed and only them.
It should be possible to pop up from a drill down situation and get back to the previous situation
with containers and relationships on exactly the same position.

**Comment by akevalion** [comment]
I think we have this behavior in this visualization
consider this nodes
![image](https://user-images.githubusercontent.com/10532890/123293236-d28b3280-d4e1-11eb-9096-1d5b49465e7e.png)
then we can collapse node2
![image](https://user-images.githubusercontent.com/10532890/123296699-e1271900-d4e4-11eb-9467-d2eb3c9b85bf.png)
and node1
![image](https://user-images.githubusercontent.com/10532890/123296750-ebe1ae00-d4e4-11eb-8d4a-c07a6d5e8308.png)
then expand it again
![image](https://user-images.githubusercontent.com/10532890/123296828-fc922400-d4e4-11eb-89c7-cb415832b284.png)

the position of expanded and collapsed nodes is the same

**Comment by bergel** [comment]
Seems to work.
