### ISSUE TITLE
Layout.

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#14]
The first time the visualisation is displayed an automatic layout can be applied.
Once this phase passed and as soon as the user changes the position of a node no automatic
layout should be applied.
New automated layout should not be applied automatically. Only on demand of the user an
automatic layout can be applied.

**Comment by akevalion** [comment]
This project uses RSFlowLayout to show the nodes the first time, then the layout is not used

**Comment by NicolasAnquetil** [comment]
Can we have an option to reapply the layout
- globally (all visualization)
- locally (for the children of one node

**Comment by akevalion** [comment]
Actually you can select one node and apply the layout, and do the same to the canvas and apply the layout for the canvas children

**Comment by NicolasAnquetil** [comment]
This issue can be closed
