### ISSUE TITLE
Relation selection.

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#16]
The user should be able to
- select the relationships coming or leaving the container and act on them (display, color...)
- select the relationships inside an expanded containers and act on them
- select the relations between a group of elements (it can be two nested elements and a
container) and other elements and act on them

**Comment by akevalion** [comment]
From Nicolas report

the specification document describes other configurations ("The visualization should offer
hooks to particularize visual aspects of edges, of border, and shapes") that we did not all
discuss yesterday. I think you could assume that everything displayed would be asked to the
configuration object, and every event could also be treated by this object.

**Comment by akevalion** [comment]
Currently elements of the visualization like HNode can handle, color, but the links does not provide styles

For that HLinkStyle has been created, do you prefer an instance of HLink have instance variables of arrow, line color, line border, etc?

**Comment by bergel** [comment]
Fixed
