### ISSUE TITLE
Actions.

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#17]
The user should be able to
- bring a menu on an entity.
- color an entity (it can be an action as in the menu)
Any operation performed via the mouse should be able to be called via an API.

**Comment by bergel** [comment]
We need to set the colors. As in:

```Smalltalk
node1 := HNode new name: 'Node1'.
node2 := HNode new name: 'Node2'.
node2 color: Color red.

subnode1 := HNode new name: 'Sub1'.
subnode2 := HNode new name: 'Sub2'.
subnode3 := HNode new name: 'Sub3'.
subnode4 := HNode new name: 'Sub4'.

node1 addAll: {subnode1. subnode2}.
node2 addAll: {subnode3. subnode4}.
	
rootNode := HNode new name: 'Root'.
rootNode addAll: { node1. node2 }.
subnode3 dependenciesToNodes: { subnode1. subnode2 }.

rootNode add: (HNode new name: 'FooBar').

rootNode open.
```

**Comment by akevalion** [comment]
Users now can use colors

![image](https://user-images.githubusercontent.com/10532890/130972429-e18e29e9-f8bb-47d5-9952-56b24647d12b.png)

**Comment by NicolasAnquetil** [comment]
Yes but the visualization is not refreshed automatically after a `#color:` message.
It requires a collapse/expand to change de color of the node

**Comment by akevalion** [comment]
I will rename HIconChanged to HNodeChangedEvent, to generalize all these events

**Comment by bergel** [comment]
This is now fixed
