### ISSUE TITLE
Icon.

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#2]
An entity should have the possibility to display a little "icon" on the top righ bottom (a little circle or
squared overlapping and decorating the visual element displaying an element. Such icon should be
only a decoration in the sense that relationships should not be attached to it.

**Comment by akevalion** [comment]
Currently an HNode has the instance variable an method of iconName:, then you can use this method to change the icon before it appear in the visualization

**Comment by akevalion** [comment]
![image](https://user-images.githubusercontent.com/10532890/125476043-e8c8573f-513a-44a9-aa7a-2533c8f2a2bc.png)

**Comment by NicolasAnquetil** [comment]
Could we change or remove the icon after the node is displayed ?

**Comment by akevalion** [comment]
use

```smalltalk
node iconName: #down 
```

This method will trigger a new event HIconChangedEvent, and it will update the view.

**Comment by NicolasAnquetil** [comment]
this issue can be closed
