### ISSUE TITLE
Owner node does not resize when subnode is expanded

### ISSUE THREAD

**Issue by NicolasAnquetil** [ObjectProfile/HierarchicalVisualizations#24]
On small Reamde example, when expanding a subnode, it expands outside the limits of its parent

![Screenshot from 2021-06-23 09-12-34](https://user-images.githubusercontent.com/14889146/123052608-4e627d80-d403-11eb-8a20-98cbba196457.png)

**Comment by akevalion** [comment]
consider
```Smalltalk
node1 := HNode new name: 'Node1'.
node2 := HNode new name: 'Node2'.
subnode1 := HNode new name: 'Sub1'.
subnode2 := HNode new name: 'Sub2'.
subnode3 := HNode new name: 'Sub3'.
subnode4 := HNode new name: 'Sub4'.

node1 addAll: {subnode1. subnode2}.
node2 addAll: {subnode3. subnode4}.
	
rootNode := HNode new name: 'Root'.
rootNode addAll: { node1. node2 }.
subnode3 dependenciesToNodes: { subnode1. subnode2 }.

subnode4 add: (HNode new name: 'Test').
subnode4 collapse.
rootNode open.

```
![image](https://user-images.githubusercontent.com/10532890/124539664-e856fc80-ddeb-11eb-8e2b-fd3151ecf17f.png)

Then this should resize the parent node
![image](https://user-images.githubusercontent.com/10532890/124539689-f278fb00-ddeb-11eb-8102-5c07aa71403e.png)
