### ISSUE TITLE
Owner node name disapear when subnode is expanded

### ISSUE THREAD

**Issue by NicolasAnquetil** [ObjectProfile/HierarchicalVisualizations#25]
On Readme small example, when expanding subnode, the name of the owner node disapear

![Screenshot from 2021-06-23 09-12-34](https://user-images.githubusercontent.com/14889146/123052754-7651e100-d403-11eb-9ac2-97868b525c61.png)

**Comment by akevalion** [comment]
I have change the way of this boxes shows now the current view is this

![image](https://user-images.githubusercontent.com/10532890/124537998-ee97a980-dde8-11eb-8478-f505b2c28c79.png)


And when you collapse it does not hide the name

![image](https://user-images.githubusercontent.com/10532890/124538081-08d18780-dde9-11eb-9311-d21901330cbd.png)
