### ISSUE TITLE
HNode>>dependenciesFromNodes: is counter intuitive

### ISSUE THREAD

**Issue by NicolasAnquetil** [ObjectProfile/HierarchicalVisualizations#26]
`A dependenciesFromNodes: {B}` draws a line from A to B

Having a dependency from something is a strange notion,
but, if we take the opposite (dependency to) it would mean that `A dependencyTo: B` would draw an arrow from B to A ?!?!

This seems counter intuitive

**Comment by akevalion** [comment]
Hi consider

```Smalltalk

| node1 node2 subnode1 subnode2 rootNode |
node1 := HNode new name: 'Node1'.
node2 := HNode new name: 'Node2'.
subnode1 := HNode new name: 'Sub2-1'.
subnode2 := HNode new name: 'Sub2-2'.
node2 addAll: {subnode1. subnode2}.
rootNode := HNode new name: 'Root'.
rootNode addAll: {node1. node2}.

subnode1 dependencyTo: node1.
subnode2 dependencyTo: node1.
rootNode open

```
![image](https://user-images.githubusercontent.com/10532890/123981622-6badc380-d990-11eb-937b-8d0cded0f5c5.png)

**Comment by NicolasAnquetil** [comment]
Much better
subnode21 depends on (has a dependency to) node1, therefore there is a link from subnode21 to node1.
That seems much more  intuitive.

**Comment by bergel** [comment]
Fixed
