### ISSUE TITLE
Expand/collapse should be inactive if there is no subnode

### ISSUE THREAD

**Issue by NicolasAnquetil** [ObjectProfile/HierarchicalVisualizations#27]

**Comment by akevalion** [comment]
The visualization does not show an expand/collapse menu item, for nodes without children
![image](https://user-images.githubusercontent.com/10532890/123382172-9f878400-d55f-11eb-8227-0c70d37c468f.png)

**Comment by bergel** [comment]
Still there...

**Comment by NicolasAnquetil** [comment]
confirming that the menu still show expand/collapse for nodes without children (readme example)
![Screenshot from 2021-08-25 08-58-59](https://user-images.githubusercontent.com/14889146/130741826-96380720-29cb-4c3b-a1e6-b01c523263c8.png)

**Comment by akevalion** [comment]
I have fixed this
![image](https://user-images.githubusercontent.com/10532890/130972269-535de8f7-7e4d-4046-9caa-f215953ffd27.png)

![image](https://user-images.githubusercontent.com/10532890/130972288-d3a2870f-a6d1-441b-8276-9f1f52a33f04.png)

**Comment by NicolasAnquetil** [comment]
Confirmed
