### ISSUE TITLE
Adding nodes to an existing visualization does not work as expected

### ISSUE THREAD

**Issue by NicolasAnquetil** [ObjectProfile/HierarchicalVisualizations#28]
On small Reamde example add a subsubnode to subnode4

then expand subnode4 -> subsubnode does not appear, subnode 4 is expanded empty
expand (collapse?) again subnode4 -> this time it is expanded correctly (with subsubnode)
collapse again subnode4 -> it goes back to the 2nd state (expanded empty)

**Comment by bergel** [comment]
a callback to some event should help here

**Comment by akevalion** [comment]
Consider
![image](https://user-images.githubusercontent.com/10532890/124537786-906ac680-dde8-11eb-8ad4-4ab2ce2c21ea.png)
Then

![image](https://user-images.githubusercontent.com/10532890/124537816-9a8cc500-dde8-11eb-98d3-5432a940fabe.png)

Now instances of HNode update the canvas.

**Comment by bergel** [comment]
Seems to work for the root node, but not for the inner node. Please check

**Comment by akevalion** [comment]
I also have fixed this issue adding nodes to the inner node
