### ISSUE TITLE
From gmail, Performance issues with HierarchicalVisualizations and moose models

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#30]
Hello,

some performance issues:

I tried a visualization on a small Model (created from All Athens
package in Moose9) :
54 packages
303 classes
7506 Methods

The visualization contains HNode for the packages, they themselves
contain HNode for the classes with inside HNodes for the methods

No dependencies between nodes at this stage

The visualization took several minutes to appear, interactions are very
slow, and collapsing a node took another 5 minutes

you can find the moose image with the visualization there:
https://www.dropbox.com/s/6ynrnyj6zwjml88/Moose9.zip
if you want to try it

nicolas

**Comment by bergel** [comment]
A ghost draggable interaction should do the think

**Comment by bergel** [comment]
A large example: `HVisualizationExamples new example09Collection open`

**Comment by akevalion** [comment]
I have updated roassal3 in order to display only visible shapes, that allows to Athens draw only visible areas.
But when you are displaying a lot of shapes the process can take several time

**Comment by bergel** [comment]
That should address the problem mentioned above.
