### ISSUE TITLE
Configuration object with composition

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#32]
From Nicolas PDF report:
configuration (Labels, Colors, Icons, layout, dealing with events, ...) is currently done
through methods that can be overriden by subclasses. It would be much better to have it
through composition: Said method is deported to another class, the visualization accepts an
object from that class, calls the method on that object to get the needed result. This is
basically the Strategy design pattern.

**Comment by akevalion** [comment]
From Stef
We discussed with nicolas and could you create little helpers so that the visualisation is not customizable only via subclassing
but via composition.
        eg: having an iconProvider, aColorProvider….

**Comment by akevalion** [comment]
From Stef

I was thinking that it could be a like a styleProvider for font, color, dash, ….

**Comment by akevalion** [comment]
From the visualization, we have to configuration objets
HLabeler, this class is used to create the title bar of each node
HLinkStyler, this class is used to create each line in the visualization

**Comment by bergel** [comment]
This should address this issue
