### ISSUE TITLE
showing/hiding links should be possible globally

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#33]
showing/hiding links should be possible globally (menu on the visualization itself) or for
individual nodes
◦ showing/hiding of links arriving to a node
◦ showing/hiding of links stemming from a node

**Comment by akevalion** [comment]
I have been working of this  issue and nodes have new menu items

![image](https://user-images.githubusercontent.com/10532890/130087746-288ad1ae-d7e7-4cc5-a40c-664c9abb61eb.png)

**Comment by bergel** [comment]
Done
