### ISSUE TITLE
Summarizing links on a container node even if it is expanded

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#34]
From Nicolas report

Summarizing links on a container node even if it is expanded. Currently, when a container
node is colapsed, the incoming/outgoing links of its inner nodes are « summarized ».
This should also be possible on -demand (menu) when the node is expanded, to simplify the
visualization while still showing the inner nodes (but not their individual links)

**Comment by akevalion** [comment]
Hierarchical visualizations have a menu item to Collapse or Expand Links, this allow to the user have this behavior, including internal links

**Comment by akevalion** [comment]
![image](https://user-images.githubusercontent.com/10532890/136463940-9b50f274-7e63-4ffb-a78b-e538501e6b3f.png)

**Comment by NicolasAnquetil** [comment]
that's the idea but it does not work for the incoming links ?
- Node1 with 2 sub-nodes
- Node2 also
- links from Subnode3 to Subnode1 and Subnode2
- "Collapse external links" on Node1

I expected to see only one arrow from Subnode3 to Node1, but I got the following:
![Screenshot from 2021-10-08 11-03-30](https://user-images.githubusercontent.com/14889146/136529395-23f63c80-5dc5-4d2e-a9e4-7887a803ad3e.png)

**Comment by akevalion** [comment]
I will review it

**Comment by akevalion** [comment]
fixed
![image](https://user-images.githubusercontent.com/10532890/136644556-11656410-2bdd-428d-9128-cb12dd1f6d82.png)

![image](https://user-images.githubusercontent.com/10532890/136644573-b0eea49b-164c-4ed0-9d13-dca3ec3cdb0e.png)
