### ISSUE TITLE
Stack of drilldowns

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#35]
From Nicolas Report

The Drill-Down functionnality was not discussed: It supposes one selected node (or inner
node) becomes the "root node" and all other nodes disapear from the visualization. It should
be possible to come back from such a situation back to the one before (stack of drilldowns)
showing again all the initial nodes and their positions.

**Comment by bergel** [comment]
This issue is not clear

**Comment by NicolasAnquetil** [comment]
The desired behaviour is the following:
1- (From readme example) visualization shows 2 nodes (`node1` and `node2`)
2- `node2` has children `subnode3` and `subnode4`
3- the user calls the "special drill-down" functionality on  `node2` (or on its content?)
4- the visualization should show only  `subnode3` and `subnode4` as the top nodes, `node1` and `node2` disappeared
5- but there is a special "drill up" functionality that allows to come back to the previous visualization

**Comment by bergel** [comment]
This behavior is actually supported. One can simply inspect a node and send the message `open` to that node. A new menu item can be easily defined. 

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/393742/132361334-d146ae1b-b6e9-44c4-a544-b5f0d3503e2d.png">

Shall we close this issue?

**Comment by NicolasAnquetil** [comment]
yep, you can close
