### ISSUE TITLE
Configurable menus

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#36]
The root node menu and the normal node menus should be also configurable.
◦ The user (we) should be able to add new entries to the menu, and he would be
responsible to implement the code to perform for this action.
◦ The user should be able to disable/re-enable the default actions of the menu (ex :
expand/colapse) for a given node

**Comment by akevalion** [comment]
Users of this package can define new menu items, and add a new entity in the visualization or a new subchild in a node
![image](https://user-images.githubusercontent.com/10532890/129133222-0177d43c-6bdf-4822-b3fe-104b10588c26.png)

**Comment by bergel** [comment]
done
