### ISSUE TITLE
Have multiple selection of nodes.

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#38]
Have multiple selection of nodes.
And being able to act on all nodes together (ex: moving them, expanding/collapsing them,
configuring the menu for the selection)

**Comment by akevalion** [comment]
related to issue #15 
The user should be able to select a group of entity and

move them together
group them inside a container
apply a layout (to be proposed) to only such entities
It is acceptable that a group with entities of different nesting level cannot be relayouted.

**Comment by akevalion** [comment]
I have been working on this, and now there is support for multiple selection nodes.

Use mouse right click to draw a rectangle to select shapes and create a new group.

This group. allows you to have actions for all nodes, moving them, expanding/collapsing them.

HGroupMenuItem is the base class you can create new subclasses to define new menu items

![image](https://user-images.githubusercontent.com/10532890/135913558-be549137-f608-48d4-8bbd-6fc0cc88bca8.png)

**Comment by NicolasAnquetil** [comment]
confirming that this is working
We asked that a new "parent node" could be defined for a group of nodes, but we will leave that for a latter time
