### ISSUE TITLE
Menu callback on edges (in addition to nodes) 

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#39]
Menu callback on edges (in addition to nodes) . Maybe simply clicking on an edge is
enough to trigger a callback.
Callbacks can be passed to the configuration object that will handle them.

**Comment by akevalion** [comment]
Users of hierarchical visualizations needs to add a new subclass to define a new action with the mouse click

![image](https://user-images.githubusercontent.com/10532890/129133997-e4d287c0-66b7-4657-9724-02b4b39ceeee.png)

**Comment by bergel** [comment]
Done
