### ISSUE TITLE
Searchable. 

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#4]
The visualisation should support a search based the entity labels. When an entity label matches
part of the label entered by the user: an action should be triggered here are two possible cases
- focus: the actual entity get redraw with a larger border
- all the entities can be slightly greyed out.
The same actions should happen on a group of entities.

**Comment by akevalion** [comment]
Currently this project uses search from roassal3 class `RSSeachInCanvasInteraction`

But this search does not work with inner shapes, only with nodes in the canvas.

![image](https://user-images.githubusercontent.com/10532890/123288049-365f2c80-d4dd-11eb-8a8b-c67d4c3ab843.png)

Is this project need a new search? or roassal3 should fix its interaction to provide search

![image](https://user-images.githubusercontent.com/10532890/123288360-7e7e4f00-d4dd-11eb-9027-bb0c4b704f31.png)

**Comment by akevalion** [comment]
Search now works on children nodes

![image](https://user-images.githubusercontent.com/10532890/136028630-97a135bf-f4b4-4e19-a63a-b4d518ed3886.png)

**Comment by NicolasAnquetil** [comment]
how can one bring up the search dialog ?

**Comment by NicolasAnquetil** [comment]
OK, with S command, I c ould search and I confirm that subnodes are searchable

1- how do you un-highlight found nodes (end of the search) ?
2- when moving a (sub-)node that was found, the coloured halo is moved with the node but also stays at the say place, so that there are 2 halos (old place + new position of the node)

**Comment by akevalion** [comment]
Hi Nicolas
1. in order to unhighlight press 'r' for reset.
2. fixed, now when moving nodes in the search result now, the halo is moved with the node

**Comment by NicolasAnquetil** [comment]
Great

But I found another bug:

- open a node with children,
- expand it
- search for this node -> it has a halo
- move one of the children to augment the size of the parent node
- the "title bar" of the node is now disconnected from the content of the node:

![Screenshot from 2021-10-08 10-51-30](https://user-images.githubusercontent.com/14889146/136527546-85a347d6-f0be-4e18-bdd9-ac67a214ec06.png)

**Comment by akevalion** [comment]
I will check this bug

**Comment by akevalion** [comment]
fixed
![image](https://user-images.githubusercontent.com/10532890/136643539-17143176-62ba-495c-975a-e594375fb8c8.png)
