### ISSUE TITLE
Edges can be disabled though a menu entry.

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#40]
Edges can be disabled though a menu entry.
Either all together (root node menu), or per node, see above.

**Comment by akevalion** [comment]
I have been worked on this, currently you can change the visibility of a link, also you can remove that dependency

![image](https://user-images.githubusercontent.com/10532890/130086433-9cf8cb18-8e91-49ef-b211-076341cf4290.png)

**Comment by bergel** [comment]
Fixed
