### ISSUE TITLE
Node Layout

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#42]
Each node should have a layout. For example, top-level node may use a different layout than
the inner nodes.

**Comment by akevalion** [comment]
consider the following code snippet:

```Smalltalk
| b |
b := HPharoNodeBuilder new.
b packageQuery: 'Hierarchical*'.
b build.
b rootNode layout: RSVerticalLineLayout new. 
b rootNode children do: [ :child | 
	child layout: RSFlowLayout new.
	child children do: [:c | 
		c layout: (RSForceBasedLayout new charge: -600; doNotUseProgressBar)
		
		 ] ].
b rootNode open
```
![image](https://user-images.githubusercontent.com/10532890/130087333-1a8d6296-8bdc-4f0c-a4d3-592775e77f10.png)

each node can have its own layout, this layout applies over a roassal3 shape

**Comment by bergel** [comment]
Seems to work well using layout that are not based on edges.
