### ISSUE TITLE
rounded corner bug:

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#47]
rounded corner bug:
Actually, the round corners are nice and may be they should become the rule and avoid the
square corners.

![image](https://user-images.githubusercontent.com/10532890/125397105-7a767c00-e37b-11eb-95c3-9497f3a10b77.png)

**Comment by akevalion** [comment]
Round corner is apply for each box

![image](https://user-images.githubusercontent.com/10532890/129134059-d0f6b3ad-e0a4-4def-855f-12a6cb32a796.png)

**Comment by bergel** [comment]
Fixed
