### ISSUE TITLE
Configuration. 

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#5]
Labels should be positionned below or above their entity. This can be parametrized via a
configuration. Font and size should be parametrized probably via the same configuration.
A configuration entity should be defined to handle such parametrisation of a visualisation.
The visualization should offer hooks to particularize visual aspects of edges, of border, and
shapes

**Comment by akevalion** [comment]
This project has HLabeler, you can create instances of this object and redifine the fontSize, text, fontFamily, and color and also de position of the label with the icon

```smalltalk
| b visualization |
b := HPharoNodeBuilder new.
b packageQuery: 'Roassal3-Chart*'.
b build.

visualization := HSimpleVisualizationBuilder new.
visualization rootNode: b rootNode.
visualization labeler: (HLabeler new 
	text: [ :node | 
		(node asString splitOn: '-') last. ];
	fontSize: [:node |
		10 + (5 * node level) ];
	fontName: 'Arial';
	color: [ :node |
		(node asString endsWith: 'Plot')
			ifTrue: [ Smalltalk ui theme backgroundColor ]
			ifFalse: [ Smalltalk ui theme textColor ] ];
	below;
	yourself).
^ visualization

```

![image](https://user-images.githubusercontent.com/10532890/125812323-bf5a8796-5988-48b4-a4ac-57fa8ebdb85e.png)

**Comment by NicolasAnquetil** [comment]
This issue can be closed

**Comment by bergel** [comment]
Update of the code:

```Smalltalk
| b visualization |
b := HPharoNodeBuilder new.
b packageQuery: 'Roassal3-Chart*'.
b build.

visualization := HSimpleVisualizationBuilder new.
visualization rootNode: b rootNode.
visualization nodeStyler: (HNodeStyler new 
	text: [ :node | 
		(node asString splitOn: '-') last. ];
	fontSize: [:node |
		10 + (5 * node level) ];
	fontName: 'Arial';
	color: [ :node |
		(node asString endsWith: 'Plot')
			ifTrue: [ Smalltalk ui theme backgroundColor ]
			ifFalse: [ Smalltalk ui theme textColor ] ];
	below;
	yourself).
visualization open
```

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/393742/132363083-db1a3462-ba5c-4680-a519-d7e82d86c2ec.png">
