### ISSUE TITLE
Hovering.

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#6]
Hovering on an element or relationships should be visible via change of color / change of width

**Comment by akevalion** [comment]
Currently you can see a change in the color of the node, being much darker than other nodes, and lines changes color from current text color to color red.

![image](https://user-images.githubusercontent.com/10532890/123288737-d5842400-d4dd-11eb-8a10-e90b6ed85515.png)

**Comment by NicolasAnquetil** [comment]
this issue can be closed
