### ISSUE TITLE
Fly by Help. 

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#7]
A fly by help should be displayed when parametrized to do so per kind of entity container, leaves.
The user should be able to

- define a new relationship between two elements.
- remove a relationship

The user should be able to create a new entity or a new container. This behavior should invoke a
parametrized action (Bloc) with the visualisation and the newly created entity

**Comment by akevalion** [comment]
From nicolas report

I mentionned that content of fly by help should be configurable

**Comment by akevalion** [comment]
Update in this issues, now is possible to add a link, entity or container to the visualization

**Comment by NicolasAnquetil** [comment]
There are two different issues here:
- configurable fly-by-help
- dynamically add entities/relationship to the visualization

**Comment by bergel** [comment]
This issue can be closed
