### ISSUE TITLE
Events. 

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#8]
Select any element (containers, leave relationships) should raise an event and the event raising
should be parametrizable to avoid to raise too many uncessary events.

**Comment by akevalion** [comment]
Currently the events are defined in the model, then many actions of the model you can do it with code or with the visual events

**Comment by akevalion** [comment]
This also is realated to the menu items, where the visualization provides a system to plug new interaction with nodes, canvas and links

**Comment by bergel** [comment]
There is the package `'Hierarchical-Model-Events'`
